### ISSUE TITLE
로그인 오류 해결

### ISSUE THREAD

**Issue by Young998904** [Young998904/Code-Catcher-BE#6]
서버 문제가 아닌 프론트 쪽 호출 문제였음. 지금은 해결

**Comment by doxxx93** [comment]
머지된 커밋들 보니까

<img width="1094" alt="image" src="https://github.com/Young998904/Code-Catcher-BE/assets/51396905/a37b25e4-f4a0-48b5-ba75-56d0d37855d5">

이거 설정하세요
